name: docs

on: push
  # Run this workflow when a review is requested on a PR, or the PR is closed
  # pull_request:
  #   types: [review_requested, closed]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install docs dependencies
        run: |
          sudo apt-get install pandoc
          pip install setuptools --upgrade
          pip install .[test,docs-build]
      # build docs
      - name: Install and build docs
        run: |
          pip install .
          cd docs
          make html
      # check code coverage
      - name: Coverage
        run: |
          coverage run --source=frank -m pytest frank/tests.py
          coverage report
          mkdir -p docs/_build/html/coverage
          coverage html -d docs/_build/html/coverage
          coverage-badge -f -o docs/_build/html/coverage/badge.svg
      # if the PR is not just closed, but also merged
      # if: github.event.pull_request.merged == false
      # deploy docs (push to gh-pages branch, which updates github.io)
      - name: Deploy docs
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # destination branch
          branch: gh-pages
