name: Docs build

on:
  # Run this workflow only when a review on a PR is requested
  pull_request:
    types: [review_requested]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install docs dependencies
        run: |
          sudo apt-get install pandoc
          pip install setuptools --upgrade
          pip install .[test,docs-build]
      - name: Install and build docs
        run: |
          pip install .
          cd docs
          make html
      - name: Coverage
        run: |
          coverage run --source=frank -m pytest frank/tests.py
          coverage report
          mkdir -p docs/_build/html/coverage
          coverage html -d docs/_build/html/coverage
          coverage-badge -f -o docs/_build/html/coverage/badge.svg
