name: Docs


on:
# Run this workflow only for commits to master
  # push:
  #   branches: [master]
# Run this workflow only when a pull request is closed
  pull_request:
    types:
      - closed

jobs:
  build:
    name: Build docs
    # Only proceed if the closed PR was also merged
    # (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges)
    if_merged:
        if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install docs dependencies
        run: |
          sudo apt-get install pandoc
          pip install setuptools --upgrade
          pip install .[test,docs-build]
      - name: Install and build docs
        run: |
          pip install .
          cd docs
          make html
      - name: Coverage
        run: |
          coverage run --source=frank -m pytest frank/tests.py
          coverage report
          mkdir -p docs/_build/html/coverage
          coverage html -d docs/_build/html/coverage
          coverage-badge -f -o docs/_build/html/coverage/badge.svg
